FROM nginx

# Pass the POL Keycloak certificate to the container for mtls
COPY /certs/pol-kc.crt /etc/nginx/conf.d/pol-kc.crt

# Pass the POL Keycloak Proxy certificate to the container for TLS for those connecting to the proxy.
COPY /certs/pol-kc-proxy.crt /etc/nginx/conf.d/pol-kc-proxy.crt
COPY /certs/pol-kc-proxy.key /etc/nginx/conf.d/pol-kc-proxy.key

# Pass the NGINX configuration file to the container
COPY /nginx/nginx.isolation.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
