events { worker_connections 1024; }

http {
    include mime.types;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /dev/stdout combined_with_time;

    error_log /dev/stderr debug;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    server {
        listen 80;

        location / {
            proxy_pass http://keycloak_http;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto http;
        }
    }

    sendfile on;

    upstream keycloak-http {
        server pol-keycloak:8080;
    }

    upstream keycloak-https {
        server pol-keycloak:8443;
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/conf.d/pol-kc-proxy.crt
        ssl_certificate_key /etc/nginx/conf.d/pol-kc-proxy.key

        location / {
            proxy_pass https://keycloak_https;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;

            proxy_pass https://keycloak_https;

            # Verify Keycloak's server cert
            proxy_ssl_server_name on;
            proxy_ssl_name keycloak.internal; # must match Keycloak cert SAN/CN
            proxy_ssl_trusted_certificate /etc/nginx/certs/ca/pol-kc.crt;
            proxy_ssl_verify on;
            proxy_ssl_verify_depth 2;

            # Present Nginx client cert to Keycloak (mTLS)
            proxy_ssl_certificate     /etc/nginx/conf.d/pol-kc-proxy.crt
            proxy_ssl_certificate_key /etc/nginx/certs/client/pol-kc-proxy.key
        }
    }
}